### ISSUE TITLE
upgrade-insecure-requests

### ISSUE THREAD

**Issue by ajeckmans** [juunas11/aspnetcore-security-headers#10]
Hi, 

Would you mind adding `upgrade-insecure-requests` to the library? 
See for more info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests

**Comment by juunas11** [comment]
This would be a good addition!

**Comment by juunas11** [comment]
New version is now on Nuget.org :) Will be visible soon.
