### ISSUE TITLE
X-Content-Security-Policy

### ISSUE THREAD

**Issue by Gaulomatic** [juunas11/aspnetcore-security-headers#2]
Is it possible to include "X-Content-Security-Policy" header?

**Comment by juunas11** [comment]
I would not mind adding this feature. Also thanks for the pull request! But we should check some things first.

[https://content-security-policy.com/](https://content-security-policy.com/) says the following:

> Note: It is known that having both Content-Security-Policy and X-Content-Security-Policy or X-Webkit-CSP causes unexpected behaviours on certain versions of browsers. Please avoid using deprecated X-* headers.

So, it could be your pull request should be changed to *only* include the X-CSP header if set, not both.

Also, some features I added to the CSP library probably are not compatible with X-CSP. So I can't approve the pull request before some further testing.
