### ISSUE TITLE
Strict-dynamic support for frames

### ISSUE THREAD

**Issue by cfletcher** [juunas11/aspnetcore-security-headers#25]
I'm trying to resolve a CSP error created by an iframe used in https://github.com/IdentityModel/oidc-client-js . I believe setting the frames value in the CSP to strict-dynamic and adding a nonce to that script will resolve my issue, but that option doesn't appear to be available for frames, only for scripts.
According to the Mozilla dev tools, its available for both
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src

Would you add/be willing to accept a PR for this?

**Comment by masterjs** [comment]
@cfletcher Not sure if this can help, but for the frame-src we used `csp.BuildCspOptions().FrameAncestors.AllowNone = true`

**Comment by cfletcher** [comment]
Thanks - @masterjs, my understanding (haven't checked) is that that'll work. But it opens us up to other scripts or code creating frames.
If we could lock it down to just our nonced/approved script, that would be more secure.

**Comment by juunas11** [comment]
Have you actually tried if adding strict-dynamic to the frame-src helps? You can add the response header manually and test your theory :) Also, I'd like to see the error you are getting.

And if that fixes the error, then I'll definitely accept a PR for that.

**Comment by cfletcher** [comment]
I'm not following how I could add strict-dynamic to the frame-src, the frame is created in javascript here:
https://github.com/IdentityModel/oidc-client-js/blob/dev/src/CheckSessionIFrame.js
We're hoping to look further into it over the next week or two - but I'm optimistic echoing some of the changes in script src recently to frame src will resolve it

**Comment by cfletcher** [comment]
Closing, a frame source of 'Self' works. My misunderstanding of the way CSPs work.
![image](https://user-images.githubusercontent.com/560153/43514743-bf6d77d6-9578-11e8-91aa-53881be41b93.png)
This was the initial error we were seeing (CSP set to no frames) but I suspected Self wouldn't work because the window had no origin.
