### ISSUE TITLE
Add support for `prefetch-src`

### ISSUE THREAD

**Issue by MrMDavidson** [juunas11/aspnetcore-security-headers#26]
Any chance of adding support for the `prefetch-src` CSP? See https://w3c.github.io/webappsec-csp/#directive-prefetch-src

**Comment by juunas11** [comment]
Thanks for the suggestion, certainly looks like a worthy addition!
I'll be sure to add it once I have some time.
I do accept PRs too ;)

**Comment by MrMDavidson** [comment]
See #27 . :)
