### ISSUE TITLE
CSP manifest-src directive not supported

### ISSUE THREAD

**Issue by marcwittke** [juunas11/aspnetcore-security-headers#32]
as described here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/manifest-src

**Comment by helloworld65** [comment]
Looking for this option as well. Is there a way to add a custom csp directive in the mean time?

**Comment by MrMDavidson** [comment]
This was affecting my application as well - I've opened a PR for this (#34) so fingers crossed it gets merged and a new nuget package goes out soon.

**Comment by juunas11** [comment]
Merge done! I'll think about a sane way to add custom directives and values, but for now I'll add support for manifest-src.
