### ISSUE TITLE
What about 'data' URIs?

### ISSUE THREAD

**Issue by Zettersten** [juunas11/aspnetcore-security-headers#36]
Refused to load the stylesheet 'data:text/css;base64,LnN3YWdnZXItdWkgLnRvcGJhciB7CiAgICBiYWNrZ3JvdW5kOiAjMDEyYjViICFpbXBvcnRhbnQ7Cn0KCi5zd2FnZ2VyLXVpIC50b3BiYXIgLmRvd25sb2FkLXVybC13cmFwcGVyIHsKICAgIGRpc3BsYXk6IG5vbmUhaW1wb3J0YW50Owp9CgogICAgLnN3YWdnZXItdWkgLnRvcGJhciAuZG93bmxvYWQtdXJsLXdyYXBwZXIgLnNlbGVjdC1sYWJlbCB7CiAgICAgICAgY29sb3I6IHdoaXRlICFpbXBvcnRhbnQ7CiAgICB9CgogICAgICAgIC5zd2FnZ2VyLXVpIC50b3BiYXIgLmRvd25sb2FkLXVybC13cmFwcGVyIC5zZWxlY3QtbGFiZWwgc2VsZWN0IHsKICAgICAgICAgICAgYm9yZGVyLWNvbG9yOiAjMDUwOTE5ICFpbXBvcnRhbnQ7CiAgICAgICAgfQ...QwdWlJNk1sSXJmOS9rZFAxV2FWamhTLzNWKzB0TnZGVVpFeFVoSFAweWwxN0k1QXdPZnhlRWF6VmRIWVl1dDhxWkVZUTRwbGg1TjU5bmlDTEdLQlZrZXRCeUNZUGxRcUlwdGJMZ3ZvZFAydFJ2Zmpod1NEUkVUMlIxeHVNYmVoNFBkOFNyem5qY2ZPUVhCd1lURDVWVTZDWUl0WWVOei9nL1ZSY04vNTVwRGxrT1dDUTVaRGxrT1dDdzVaWDhUL0Fnd0FUS2p3UVpGUXZxNEFBQUFBU1VWT1JLNUNZSUk9Jykgbm8tcmVwZWF0OwogICAgICAgIHdpZHRoOiAxMTVweDsKICAgICAgICBoZWlnaHQ6IDQ4cHg7CiAgICAgICAgcGFkZGluZzogMCAhaW1wb3J0YW50OwogICAgfQoKICAgIC5zd2FnZ2VyLXVpIC5pbmZvIC50aXRsZSArIGEgewogICAgICAgIGRpc3BsYXk6IG5vbmU7CiAgICB9' because it violates the following Content Security Policy directive: "default-src *". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by dine** [comment]
did you try `.From("data:")`?
