### ISSUE TITLE
HstsOptions should work with Timespan class

### ISSUE THREAD

**Issue by MovGP0** [juunas11/aspnetcore-security-headers#4]
`HstsOptions` should be refactored to use a `Timespan` instead of an `int` and may be immutable too:

```csharp
var options = new HstsOptions(Timespan.FromDays(30), includeSubDomains: false, preload: false);
app.UseHsts(options);
```

**Comment by juunas11** [comment]
Good suggestion! I'll have a look later today for what the API could look like.

**Comment by juunas11** [comment]
Alright, so how about we do this:

Remove the `Seconds` property.

Add a new property `Duration` of type `TimeSpan`.

Make all the properties read-only.

Make a constructor with default values for everything except the duration.

The options class would then look like this:

````
public class HstsOptions
{
    public HstsOptions(TimeSpan duration, bool includeSubDomains = false, bool preload = false)
    {
         Duration = duration;
         IncludeSubDomains = includeSubDomains;
         Preload = preload;
    }

    public TimeSpan Duration { get; }

    public int DurationSeconds => (int) Duration.TotalSeconds;

    public bool IncludeSubDomains { get; }

    public bool Preload { get; }
}
````

**Comment by MovGP0** [comment]
Seems much cleaner this way. 
You shouldn't derive from entities. So I guess you can mark this entity as `sealed` too.  

Also, this is a breaking change, so you need a new 'minor' version number.

**Comment by juunas11** [comment]
I agree with the new minor version, but I don't agree with `sealed`. I do not think it brings value to the library. I can understand why `System.String` is sealed, but this is not a case like that.
