### ISSUE TITLE
Core 2.0 upgrade

### ISSUE THREAD

**Issue by xperiandri** [juunas11/aspnetcore-security-headers#6]
Could you make a preview package for Core 2.0?

**Comment by juunas11** [comment]
Sure :) I'm a bit busy in the coming weeks, but after that I should be able to make one.

**Comment by xperiandri** [comment]
Cool, thanks

**Comment by juunas11** [comment]
Actually, now that I thought about this request for a moment, doesn't it already work in 2.0?
The library is built on .NET Standard 1.5 and does not need to be higher.

I can update the sample and test projects to 2.0 of course.

**Comment by xperiandri** [comment]
That would be nice
