### ISSUE TITLE
Access the nonce value

### ISSUE THREAD

**Issue by tlnorwood** [juunas11/aspnetcore-security-headers#61]
I am generating a script dynamically in C# code, and I want to be able to provide the nonce.  Is there a way to access the nonce's value in my C# code?

**Comment by juunas11** [comment]
Yeah, you should be able to inject [ICspNonceService](https://github.com/juunas11/aspnetcore-security-headers/blob/4290c91b2fdebbe1c116ec43a3c8f5e1ed6629d4/src/Joonasw.AspNetCore.SecurityHeaders/Csp/ICspNonceService.cs) to anywhere in your code and get the value from there. It'll be the same as what is written in the output.
