### ISSUE TITLE
Adding nonce to a div element with inline style

### ISSUE THREAD

**Issue by henningst** [juunas11/aspnetcore-security-headers#9]
The nonce tag helper can add a nonce to `style` and `script` tags, but not to `div` elements. Are there any reasons why a nonce can't be added to `div` elements? I have a few cases where div elements contains inline style where this could be useful. Would you accept a PR to add support for this?

**Comment by juunas11** [comment]
It would be nice if CSP worked that way, however according to the [W3C spec](https://w3c.github.io/webappsec-csp/2/#script-src-nonce-usage):

> This same value is then applied as a nonce attribute to each script element that ought to be executed.

Reading that, it seems like a nonce can only be applied on a `style` or `script` element.

**Comment by henningst** [comment]
Thanks for your response. I was afraid a limitation like that was the reason this wasn’t already added to the tag helper.

**Comment by gajanan999** [comment]
how to apply nonce to style element

if I have the following html
I have tried 
this

<html>
       <div style="nonce:nonce-azJ3ZGZhejhpeGE=; color: red; background-color: yellow;" >hello</div>
</html>

<html>
       <div style="nonce:azJ3ZGZhejhpeGE=; color: red; background-color: yellow;" >hello</div>
</html>


<html>
       <div style="color: red; background-color: yellow;" nonce="azJ3ZGZhejhpeGE=">hello</div>
</html>

but nothing is working, What is exact syntax?

**Comment by juunas11** [comment]
I tried checking for this syntax but couldn't find anything either. You could instead specify a CSS class and use a `<style>` element for the rules.
